### PR TITLE
Fix showing stack status notification on opening existing CloudFormation stack (#2157)

### LINKED ISSUE #2157: CloudFromation tool window should not show terminal state upon opening
If the cloud formation stack is already in a terminal state, we should not show it in the notification popup upon opening the window

### PR DESCRIPTION
**Pull request by hunterwerlla**
## Related issues
#2157

## License
I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: jetbrains-core/src/software/aws/toolkits/jetbrains/services/cloudformation/stack/Updater.kt [hunk 1]
```diff
@@ -96,13 +96,16 @@ class Updater(
         val newStackStatusType = newStackStatus.type
         val newStackStatusNotInProgress = newStackStatusType !in setOf(StatusType.UNKNOWN, StatusType.PROGRESS)
 
-        // Stack changed to some "final" status just now, notify user
-        val stackSwitchedToFinalStatus = previousStackStatusType != newStackStatusType && newStackStatusNotInProgress
+        // Stack changed to some "final" status just now, notify the user. Don't show a notification if the state
+        // happened at creation time, which is distinguished by stackStatus being null
```
Comment (rli) [inline jetbrains-core/src/software/aws/toolkits/jetbrains/services/cloudformation/stack/Updater.kt:100]: probably want some tests here, but doesn't look that testable :(

**Review by rli — APPROVED** [review]
