### PR TITLE
Ignore .DS_Store when building Lambda zip

### LINKED ISSUE #725: Error running '[Local] LambdaFunc': duplicate entry .DS_Store
**Describe the bug**
When I try to run a lambda via run/debug config I get an error

**To reproduce**
Create config, click debug

**Expected behavior**
It works

**Screenshots**
image

**Your Environment**
 - OS: mcOS Mojave 10.12
 - JetBrains' Product:  PyCharm
 - JetBrains' Product Version: 2018.3.2
 - Toolkit Version:1.2
 - SAM CLI Version: 0.10.0 
 - JVM/Python Version: 3.6

**Additional context**

### PR DESCRIPTION
**Pull request by abrooksv**
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Related Issue(s)
Fixes #725

## Testing
New unit test

## License
I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: jetbrains-core/src/software/aws/toolkits/jetbrains/services/lambda/python/PythonLambdaPackager.kt [hunk 1]
```diff
@@ -86,14 +79,22 @@ class PythonLambdaPackager : LambdaPackager {
...
                 mappings[file.path] = relativeLocation
                 file.inputStream.use { fileContents ->
                     zip.putNextEntry(relativeLocation, fileContents)
                 }
             }
         }
     }
+
+    private companion object {
+        val FILE_NAME_BLACKLIST = setOf(".DS_Store")
```
Comment (zhangzhx) [inline jetbrains-core/src/software/aws/toolkits/jetbrains/services/lambda/python/PythonLambdaPackager.kt]: Why do we remove the `thumbs.db` file?

Comment (abrooksv) [reply jetbrains-core/src/software/aws/toolkits/jetbrains/services/lambda/python/PythonLambdaPackager.kt]: Seemed on that I found no reference to thumbs.db in IJ codebase so wasn't sure it was actually needed
