### PR TITLE
Fixing delete application

### LINKED ISSUE #504: Delete application doesn't work

### PR DESCRIPTION
**Pull request by kiiadi**
Fixes #504

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

### CODE REVIEW

File: jetbrains-core/src/software/aws/toolkits/jetbrains/core/DeleteResourceAction.kt [hunk 1]
```diff
@@ -18,7 +18,7 @@ import software.aws.toolkits.resources.message
 abstract class DeleteResourceAction<in T : AwsExplorerResourceNode<*>>(text: String) : SingleResourceNodeAction<T>(text, icon = AllIcons.Actions.Cancel),
     DumbAware {
     final override fun actionPerformed(selected: T, e: AnActionEvent) {
-        val resourceName = selected.toString()
```
Comment (abrooksv) [inline jetbrains-core/src/software/aws/toolkits/jetbrains/core/DeleteResourceAction.kt]: ... I hate you toString()!
