### PR TITLE
Fixing several usability issues with the CloudFormation stack UI

### LINKED ISSUE #798: Clicking on a CFN stack to open the viewer multiple times opens multiple tabs
**To reproduce**
1. Double click on a CFN tack to open viewer
2. Click on same stack again

**Expected behavior**
If tab is open, focus it. Else open new tab and focus that.

### LINKED ISSUE #799: Double clicking a stack to view it also expands the node
**Describe the bug**
The issue is that a CFN stack is not a leaf node since we expand supported sub-resources. We need to decide if we should just switch Opens stack to a context menu or find some other fix.

Double clicking to expand is standard UX for a JTree

**To reproduce**
1. Double click a CFN stack

### PR DESCRIPTION
**Pull request by kiiadi**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Description

Made several usability updates to the Stack Viewer:
- Removing status icons from event-history, replacing with color similar to the Console UI
- Preventing multiple tabs opening for the same stack - fixes #798
- Switching explorer entry-point to be a right-click rather than double-click - fixes #799
- Adding status reason to the event-history

## Motivation and Context

Usability

## Related Issue(s)

#798 
#799 

## Testing

`gradlew check`

## Screenshots (if appropriate)
Screen Shot 2019-05-10 at 10 31 46 AM
Screen Shot 2019-05-10 at 10 31 33 AM

## Checklist

- [x] I have read the **README** document
- [x] I have read the **CONTRIBUTING** document
- [x] Local run of `gradlew check` succeeds
- [x] My code follows the code style of this project
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed
- [x] A short description of the change has been added to the **CHANGELOG**

## License
I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: jetbrains-core/src/software/aws/toolkits/jetbrains/services/cloudformation/CloudFormationExplorerNodes.kt [hunk 1]
```diff
@@ -89,7 +88,6 @@ class CloudFormationStackNode(project: Project, val stackName: String, private v
 
     override fun onDoubleClick(model: DefaultTreeModel, selectedElement: DefaultMutableTreeNode) {
         super.onDoubleClick(model, selectedElement)
-        openStack(nodeProject, stackName)
     }
```
Comment (zhangzhx) [inline jetbrains-core/src/software/aws/toolkits/jetbrains/services/cloudformation/CloudFormationExplorerNodes.kt]: I think we can remove this method as it does nothing more.

Comment (kiiadi) [reply jetbrains-core/src/software/aws/toolkits/jetbrains/services/cloudformation/CloudFormationExplorerNodes.kt]: https://github.com/aws/aws-toolkit-jetbrains/pull/956/files#diff-510cc4017b37da840e516696085651fbL23 - it's gone!
